""" tables changed

Revision ID: 0844d29b17b6
Revises: ae6e2f1fb638
Create Date: 2026-09-29 17:40:13.441587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0844d29b17b6'
down_revision: Union[str, Sequence[str], None] = 'ae6e2f1fb638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_jobs_geo_location'), table_name='jobs', postgresql_using='gist')
    op.drop_table('jobs')
    op.drop_index(op.f('idx_users_geo_location'), table_name='users', postgresql_using='gist')
    op.drop_table('users')
    op.drop_table('workers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('expected_hourly_wage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('workers_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workers_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('workers_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('profile_img', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('geo_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.Column('role_id', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=False),
    sa.Column('language', postgresql.ENUM('MAL', 'ENG', 'TAM', 'TEL', 'HIN', name='languageenum'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('phone', name=op.f('users_phone_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_users_geo_location'), 'users', ['geo_location'], unique=False, postgresql_using='gist')
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('geo_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.Column('discription', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.Column('audio', sa.VARCHAR(length=225), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('worker_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('POSTED', 'ACCEPTED', 'STARTED', 'COMPLETED', 'CANCELLED', name='jobstatusenum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('jobs_customer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('jobs_worker_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('idx_jobs_geo_location'), 'jobs', ['geo_location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###
