"""create user table

Revision ID: 74e607ba5cb5
Revises: df295d777f07
Create Date: 2026-09-21 02:01:05.929643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '74e607ba5cb5'
down_revision: Union[str, Sequence[str], None] = 'df295d777f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=225), nullable=True),
    sa.Column('password_hash', sa.String(length=225), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geo_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('address', sa.String(length=225), nullable=False),
    sa.Column('profile_img', sa.String(length=225), nullable=True),
    sa.Column('verification_proof', sa.String(length=225), nullable=True),
    sa.Column('exp_yrs', sa.Float(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('service_radius', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('total_rating', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_geo_location', 'user', ['geo_location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_geo_location', table_name='user', postgresql_using='gist')
    op.drop_table('user')
    # ### end Alembic commands ###
